// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pdv.Infra.Data.Context;

#nullable disable

namespace Pdv.Infra.Data.Migrations
{
    [DbContext(typeof(PdvDbContext))]
    [Migration("20260826222454_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pdv.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ReferedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ReferedTo")
                        .HasDatabaseName("IX_Companies_Name_ReferedTo");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Devolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Devolutions_OrderId");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("IX_Devolutions_OrderId_CreatedAt");

                    b.ToTable("Devolutions", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.DevolutionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DevolutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DevolutionId")
                        .HasDatabaseName("IX_DevolutionItems_DevolutionId");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("IX_DevolutionItems_OrderItemId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("DevolutionItems", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Orders_UserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Orders_Status_CreatedAt");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItems_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_OrderItems_ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderPayments_OrderId");

                    b.HasIndex("PaymentMethod", "CreatedAt")
                        .HasDatabaseName("IX_OrderPayments_PaymentMethod_CreatedAt");

                    b.ToTable("OrderPayments", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cod")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Cod");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("StockId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.SeelingPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "CreatedAt")
                        .HasDatabaseName("IX_SeelingPrices_ProductId_CreatedAt");

                    b.ToTable("SeelingPrices", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Stocks_CompanyId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Stocks_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Stocks_UpdatedAt");

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .HasDatabaseName("Suppliers_Cnpj");

                    b.HasIndex("Name")
                        .HasDatabaseName("Suppliers_Name");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.SupplierPurchasing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("IX_SuppliersPurchasing_SupplierId");

                    b.HasIndex("ProductId", "CreatedAt")
                        .HasDatabaseName("IX_SuppliersPurchasing_ProductId_CreatedAt");

                    b.ToTable("SuppliersPurchasing", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Name", "RoleId")
                        .HasDatabaseName("IX_Users_Name_RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Devolution", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Order", null)
                        .WithMany("Devolutions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdv.Domain.Entities.DevolutionItem", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Devolution", null)
                        .WithMany("DevolutionItems")
                        .HasForeignKey("DevolutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pdv.Domain.Entities.OrderItem", null)
                        .WithMany("DevolutionItems")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdv.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pdv.Domain.Entities.Product", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdv.Domain.Entities.OrderPayment", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Order", null)
                        .WithMany("OrderPayments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Product", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Stock", null)
                        .WithMany("Products")
                        .HasForeignKey("StockId");
                });

            modelBuilder.Entity("Pdv.Domain.Entities.SeelingPrice", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Product", null)
                        .WithMany("SeelingPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Stock", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Company", null)
                        .WithMany("Stocks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdv.Domain.Entities.SupplierPurchasing", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Product", null)
                        .WithMany("SuppliersPurchasing")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pdv.Domain.Entities.Supplier", null)
                        .WithMany("SupplierPurchasings")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdv.Domain.Entities.User", b =>
                {
                    b.HasOne("Pdv.Domain.Entities.Company", null)
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pdv.Domain.Entities.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Company", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Devolution", b =>
                {
                    b.Navigation("DevolutionItems");
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Order", b =>
                {
                    b.Navigation("Devolutions");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("Pdv.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("DevolutionItems");
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("SeelingPrices");

                    b.Navigation("SuppliersPurchasing");
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Stock", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Pdv.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("SupplierPurchasings");
                });
#pragma warning restore 612, 618
        }
    }
}
